### ISSUE TITLE
Crash in gdImageFlipVertical for palette based images

### ISSUE THREAD

**Issue by pleuba** [libgd/libgd#165] opened 2015-06-03 07:06 UTC
In latest release gd-2.1.1, the gdImageFlipVertical function crashes for palette based images, because the code incorrectly accesses the tpixels pointer that is null (used only for truecolor image).

The gdIageFlipHorizontal does NOT have the same problem.

**Comment by vapier** [comment] 2015-06-03 08:27
duplicate of #148

**Closed by vapier** 2015-06-03 08:27 UTC
Labels: duplicate
