### ISSUE TITLE
Fatal and normal libjpeg/ibpng errors not distinguishable

### ISSUE THREAD

**Issue by cmb69** [libgd/libgd#338] opened 2016-11-09 17:08 UTC
This issue has been reported in <https://bugs.php.net/bug.php?id=73479>. Basically it boils down to [fatal_jpeg_error()](https://github.com/libgd/libgd/blob/gd-2.2.3/src/gd_jpeg.c#L100-L119) raising GD_ERROR regardless whether carrying on is possible or not. It seems to me that in the former case a GD_WARNING would be more appropriate, so that clients are able to distinguish both cases. An alternative might be to introduce GD_CRIT to indicate the "extremely fatal error".

[gdPngErrorHandler()](https://github.com/libgd/libgd/blob/gd-2.2.3/src/gd_png.c#L52-L74) has the same issue.

**Comment by pschlan** [comment] 2017-05-13 13:31
I think this issue is not getting enough attention.

This change of behavior can lead to significant problems in PHP-based web services. Imagine a background process which processes pictures uploaded by users. Now that a fatal error is issued, it's not possible to handle the case were users uploaded corrupted files anymore. This effectively causes the background process to crash and the whole application to stop working.

In my opinion this needs to be addressed urgently.

**Comment by sezeryalcin** [comment] 2017-06-02 07:11
Invalid content should not trigger a fatal error:

PHP Fatal error:  imagecreatefromstring(): gd-jpeg: JPEG library reports unrecoverable error: Invalid JPEG file structure: two SOI markers in ...

**Comment by byWulf** [comment] 2017-08-03 09:54
How is this ticket going? As I can see, in November a fix was already committed, but not yet merged.

We currently get also a fatal error in php when trying to open a corrupted image and cannot react properly to this error because it is a fatal error and no recovery from it is possible.

`imagecreatefromstring(): gd-jpeg: JPEG library reports unrecoverable error: Unsupported marker type 0x84`

**Comment by sezeryalcin** [comment] 2017-08-03 10:00
I have been working on some alternative ways to detect bad jpeg using exif information. However no definitive solution yet.
I experimented with external tools like imagemagick. They can be used to validate jpeg files/data but in my case. it becomes too slow.
This is breaking PHP's promise to return false if data is corrupt.

imagecreatefromstring ( string $image )
Return Values:
An image resource will be returned on success. 
FALSE is returned if the image type is unsupported, the data is not in a recognised format, or the image is corrupt and cannot be loaded.

**Comment by cmb69** [comment] 2017-08-03 10:06
> As I can see, in November a fix was already committed, but not yet merged.

I think PR #346 should be merged into GD-2.2, even though it constitutes a BC break.

**Closed** 2017-08-27 15:49 UTC

**Comment by sezeryalcin** [comment] 2017-09-04 19:14
Great. What's the timeline/version we should expect to see this fix with PHP?

**Comment by cmb69** [comment] 2017-09-04 21:47
> What's the timeline/version we should expect to see this fix with PHP?

PHP's bundled libgd was never affected.

**Comment by sezeryalcin** [comment] 2017-09-06 14:30
Sorry, I didn't understand this.
I have PHP 5.6.30 on debian arm and this is definitely an issue. What does this fix?

I have GD module details here:
gd
GD Support => enabled
GD headers Version => 2.1.1-dev
FreeType Support => enabled
FreeType Linkage => with freetype
FreeType Version => 2.5.2
GIF Read Support => enabled
GIF Create Support => enabled
JPEG Support => enabled
libJPEG Version => 6b
PNG Support => enabled
libPNG Version => 1.2.50
WBMP Support => enabled
XPM Support => enabled
libXpm Version => 30411
XBM Support => enabled
WebP Support => enabled

**Comment by cmb69** [comment] 2017-09-06 14:41
> GD headers Version => 2.1.1-dev

That appears pretty old. You'd need 2.2.5.

**Comment by samthomson** [comment] 2017-10-10 20:02
I have the same problem. PHP 7.1
![image](https://user-images.githubusercontent.com/6588340/31407845-4f1e5c0a-adfe-11e7-8104-fa7e1aa29eb5.png)

**Comment by cmb69** [comment] 2017-10-10 20:25
@samthomson PHP's bundled libgd has never been affected by this issue.

**Comment by samthomson** [comment] 2017-10-10 20:41
Ah ok, thanks.
Maybe you have some ideas...

code:
![image](https://user-images.githubusercontent.com/6588340/31409387-a2a7692a-ae03-11e7-8fcb-19bef3b0d16c.png)

error:
![image](https://user-images.githubusercontent.com/6588340/31409354-7e5b5bf8-ae03-11e7-809c-6b6fd0d12180.png)

using php 7.1 where gd.jpeg_ignore_warning is enabled by default

Do you have any ideas?

**Comment by cmb69** [comment] 2017-10-10 20:50
Can you publish the image that causes this error somewhere?

**Comment by samthomson** [comment] 2017-10-10 20:53
@cmb69  Sure, thanks for helping. https://ufile.io/5qinu

**Comment by cmb69** [comment] 2017-10-10 21:41
@samthomson  Quite interestingly, the image can't be opened by ImageMagick's display nor by Gimp 2. Some other applications (for instance, LibreOffice Draw) display the image fine. That *might* indicate an issue in libjpeg(-turbo).

I will try to investigate further.

**Comment by samthomson** [comment] 2017-10-11 07:43
Yes, my experience is the same. I don't mind that I can't process it, my goal would be to identify it as corrupt in code such that I can throw an exception, the problem is that a fatal error is raised.

**Comment by sezeryalcin** [comment] 2017-10-11 07:49
@samthomson I was able to mitigate this issue by downloading latest source code from php.net and compiling myself. Not an easy task as dependencies must be installed and configuration options should be set. As @cmb69  pointed out,bundled libgd from php.net does not fatally fail on invalid images, it just returns FALSE with imagecreatefrom* functions.

**Comment by cmb69** [comment] 2017-10-11 12:05
I tested with current PHP-7.1 with bundled libgd and libgd 2.2.5; both exhibit the same behavior. Test script:
````php
<?php

var_dump(imagecreatefromjpeg(__DIR__ . '/440.jpg'));
````
Output:
````
Warning: imagecreatefromjpeg(): gd-jpeg: JPEG library reports unrecoverable error: Unsupported marker type 0xac in /parent/440.php on line 3

Warning: imagecreatefromjpeg(): '/parent/440.jpg' is not a valid JPEG file in /parent/440.php on line 3
bool(false)
````
So I can't reproduce a fatal error. This might be caused by Symphony by elevating the warning to a fatal error. Please either try without Symphony, or add the error suppression operator `@`.

With regard to gd.jpeg_ignore_warning: this appears to be a documentation issue. Actually, it is not supposed to suppress PHP warnings, but rather libjpeg(-turbo) warnings. However, libjpeg(-turbo) reports an unrecoverable error, not a warning.

Anyhow, this doesn't appear to be related to GD at all, so would better be addressed in the [PHP bug tracker](https://bugs.php.net/), if at all.

**Comment by samthomson** [comment] 2017-10-11 20:57
@sezeryalcin @cmb69 Thanks for your help. 
You're right, the issue is not with imagecreatefromjpeg but elsewhere in a framework I am using that seems to be catching warnings and throwing fatal errors. I will debug further to isolate the problem and create an issue elsewhere with the appropriate framework.
