### ISSUE TITLE
gdAssertImageEquals() can't be used

### ISSUE THREAD

**Issue by cmb69** [libgd/libgd#228] opened 2016-06-13 10:10 UTC
gdAssertImageEquals() and gdAssertImageEqualsMsg() are implemented as macros ([in gdtest.h](https://github.com/libgd/libgd/blob/gd-2.2.0/tests/gdtest/gdtest.h#L55-L56)) which resolve to CuAssertImageEquals_LineMsg(). However, this symbol is not defined in libgd (GD-2.2 as well as master), at least when using the classical toolchain (configure & make).

Either a dependency is not documented (or I've overlooked it), or the definition is simply missing.

**Comment by vapier** [comment] 2016-06-13 13:51
`gdtest.h` is only used by the testsuite, is not installed, and all tests link in `gdtest.c`.  it is, by design, not in libgd.

so i'm not sure what the question is here.

**Comment by cmb69** [comment] 2016-06-13 14:20
The issue is, that the seemingly useful macros gdAssertImageEquals() and gdAssertImageEqualsMsg() can't be (and are currently not) used in the testsuite. If these macros should not be used, we should remove [their definitions](https://github.com/libgd/libgd/blob/gd-2.2.0/tests/gdtest/gdtest.h#L55-L56) to avoid confusion.

**Comment by vapier** [comment] 2016-06-13 16:11
sorry, i thought you were talking about `gdAssertImageEqualsToFile`

the `gdAssertImageEquals` funcs can probably just be changed to use `gdTestImageCompareToImage`

**Comment by pierrejoye** [comment] 2016-06-14 18:45
I am surely to blame, a remaining of the rewrite of the tests tool.

It could or should use gdTestImageCompareToImage

**Comment by vapier** [comment] 2016-06-15 16:19
fixed in commit f9a4e53a37c87615eda3e7cbd606f958a5a87dae and commit e4bddc719b0930059a724b0ba6d1f2b8232c67e9

**Closed by vapier** 2016-06-15 16:19 UTC
Labels: bug, help wanted
