### ISSUE TITLE
Fixed bug #75571: Potential infinite loop in gdImageCreateFromGifCtx

### ISSUE THREAD

**Issue by totemofwolf** [libgd/libgd#431] opened 2018-01-31 10:51 UTC
[https://gist.githubusercontent.com/anonymous/2c5331292f9e77e694ad9dd8901a3a11/raw/d8e3cc4270fe2ff32ee95bab2d6b416ae0f6d569/75571.diff

[75571.diff.txt](https://github.com/libgd/libgd/files/1681377/75571.diff.txt)

**Comment by cmb69** [comment] 2018-01-31 11:40
Duplicate of #420.

**Closed by cmb69** 2018-01-31 11:40 UTC
