### ISSUE TITLE
Travis builds on OS X fail due to missing config/ltmain.sh due to glibtoolize failing: /usr/local/Library/ENV/4.3/sed: No such file or directory

### ISSUE THREAD

**Issue by cmb69** [libgd/libgd#266] opened 2016-07-19 10:43 UTC
See, for instance, <https://travis-ci.org/libgd/libgd/jobs/145786164#L134>.

It seems that there is a package missing.

**Comment by vapier** [comment] 2016-07-19 10:59
AM_ICONV is provided by gettext.  if we're using iconv, then we'd prob need other l10n tools gettext provides too ...

**Comment by cmb69** [comment] 2016-07-19 15:52
> AM_ICONV is provided by gettext.

However, [gettext is supposed to be installed](https://github.com/libgd/libgd/blob/master/travis/main.sh#L39-L40). :?

**Comment by pierrejoye** [comment] 2016-07-20 05:35
It breaks since some time already. We did not change anything on travis scripts so I suppose something changed on travis  osx config.

**Comment by cmb69** [comment] 2016-07-20 11:38
I'm not sure how this can be resolved (no expirierence with OS X), but I would suggest to disable the OS X Travis checks for now, because they will fail anyway, and that causes overhead when checking the Travis reports.

**Comment by vapier** [comment] 2016-07-20 12:00
could enable tracing when autotools runs.  gettext might not be installing its m4 file into the place where aclocal (automake) searches.

**Comment by vapier** [comment] 2016-07-21 15:40
the problem isn't gettext.  if you look at the [previous build that passed](https://travis-ci.org/libgd/libgd/jobs/145038589), you'll see it had the same AM_ICONV warning.  if you compare it to the [first build that failed](https://travis-ci.org/libgd/libgd/jobs/145322783), you'll see the issue is:

```
/usr/local/bin/glibtoolize: line 401: /usr/local/Library/ENV/4.3/sed: No such file or directory
...
configure.ac:68: error: required file 'config/ltmain.sh' not found
```

indeed, missing libtool will be problematic because we rely on that for all object building.  however, i think what @pierrejoye said is unchanged -- something changed w/the Travis CI env independent of our code and that broke things.

i think the underlying bug is the same as Homebrew/legacy-homebrew#43874.  we can probably deploy the same hack as suggested there:

```
brew uninstall libtool
brew install libtool
```

i'll try it on my libgd branch and see if it fixes things before pushing to libgd master

**Comment by pierrejoye** [comment] 2016-07-21 15:44
I mailed travisci about it. Let see what they say :)

**Comment by vapier** [comment] 2016-07-21 18:12
OS X builds are passing on travis now with that simple workaround.  that should unblock us at least while the travis guys sort things out.

**Comment by pierrejoye** [comment] 2016-07-23 04:10
Thanks :)

We can close this issue. The issue was what you said. The reply from travis support:

"
Hi Pierre!

Thank you for writing in and point us to this issue! We apologize for the inconvenience. Cause is this issue, which has not been closed yet. 

The results is, that there is an issue on some of our OS X images with `glibtool`. One user kindly reported to us that reinstalling `libtool` works. To achieve this, please try:

before_install:
  - brew uninstall libtool && brew install libtool
  - your other before_install steps

We would appreciate a short feed back if this works for you. 

This is of course a temporary workaround until the time we get around to update the OS X images.

Sorry again for the inconvenience. Wish you a nice day!

Joep
"

**Closed by pierrejoye** 2016-07-23 04:10 UTC
Labels: bug, build
