### ISSUE TITLE
Test failures on 32-bit Cygwin

### ISSUE THREAD

**Issue by kbrow1i** [libgd/libgd#480] opened 2018-11-11 20:38 UTC
I'm getting two test failures on 32-bit Cygwin (after locally fixing the crash that I reported in issue #479).  The tests all pass on 64-bit Cygwin.  I'm attaching the test suite log.  Please let me know if there's anything I can do to help track this down.
[test-suite.log](https://github.com/libgd/libgd/files/2569797/test-suite.log)

**Comment by cmb69** [comment] 2018-11-12 10:54
Please post the respective `*_diff.png` and `*_out.png` images (e.g. `tests/gdimagegrayscale/basic_diff.png`).

**Comment by kbrow1i** [comment] 2018-11-12 12:52
Attached.

![basic c_21_diff](https://user-images.githubusercontent.com/2318316/48348608-d713bd00-e64f-11e8-9846-d6a30cf40a99.png)
![basic c_21_out](https://user-images.githubusercontent.com/2318316/48348626-e1ce5200-e64f-11e8-8414-d598882a5636.png)
![bug00201 c_68_diff](https://user-images.githubusercontent.com/2318316/48348627-e1ce5200-e64f-11e8-814f-4d0ff1063aab.png)
![bug00201 c_68_out](https://user-images.githubusercontent.com/2318316/48348629-e3981580-e64f-11e8-97f3-c0e3c1d9fd04.png)

**Comment by cmb69** [comment] 2018-11-12 13:45
Thanks.

The `gdimagegrayscale/basic.c` failure is a duplicate of #359. Please check whether https://github.com/libgd/libgd/issues/242#issuecomment-228959163 would solve the problem.

The `gdimagecopyresampled/bug00201.c` also look like rounding issues. Maybe adding the flags fix this as well.

**Comment by cmb69** [comment] 2018-11-13 11:32
Well, the following might not be the best solution:
https://github.com/libgd/libgd/blob/434b639d53a8fa711bc7697944e3b05b05cdecd0/src/gd_filter.c#L275
Shouldn't we round (i.e. add `0.5`) instead of truncate here?

**Comment by kbrow1i** [comment] 2018-11-13 20:29
I tried making that change, but the test still fails.  Now the log says

gdimagegrayscale/basic.c:21: Total pixels changed: 134400 with a maximum channel  difference of 131.                                                                

Previously the total pixels changed was 55200, so I guess this is actually slightly worse.

**Comment by cmb69** [comment] 2018-11-13 21:37
That is to be expected – the expected image would have to be regenerated. However, there may still be differences between different architectures (from looking at the diff image, I think the differences don't matter much in practise; fixing the test to be more tolerant is likely the proper fix, see #216). My comment was rather meant as general suggestion.

**Comment by pierrejoye** [comment] 2021-08-28 08:37
We won't change this stable code now. The results is not wrong per se, a +/- 1 error on one channel value. 32bit arch is really a very tiny percentage of the used architecture these days.

Also please note we do test now mingw32 (see the CI in the .github/workflow) as well as visual studion.

**Closed by pierrejoye** 2021-08-28 08:37 UTC
Labels: tests
