### ISSUE TITLE
System Frozen

### ISSUE THREAD

**Issue by OnurTasliogluu** [libgd/libgd#348] opened 2016-11-17 20:34 UTC
Hello,

./gdtopng my_payload /dev/null

System frozen. I sent you the payload.

Sample Php Script:

<?php
$png = imagecreatefromgd($argv[1]);
?>

Regards,

Author: Onur TAŞLIOĞLU

**Comment by cmb69** [comment] 2016-11-18 10:11
This is a duplicate of issue #340.

**Comment by cmb69** [comment] 2016-11-18 10:12
Oh, maybe not. I'm going to check.

**Comment by cmb69** [comment] 2016-11-18 11:34
Well, the image reports a size of 65528*32769 pixels, which amounts to a memory usage of roughly 2 GB. Allocating this huge amount of memory can take a while (particularly if memory has to be swapped), but after a few seconds, my system reports:
`Input is not in GD format`

I'm not sure whether this qualifies as bug, and I'm somewhat uncomfortable to place an arbitrary hard-coded size restriction to gdImageCreate(TrueColor)(). Maybe we should make that configurable?

**Comment by Honor-Onur** [comment] 2016-11-18 16:45
Hmm yes, The problem is memory usage.
Maybe it can be checked but this subject that needs attention.

I tested the file 4Gb memory. The problem did not occur.
Result:
Input is not in GD format!
But 1GB memory gives an error in memory.

**Comment by vapier** [comment] 2018-01-31 03:28
so not a bug ?  we can deal with very large images via #122.

**Closed by vapier** 2018-01-31 03:28 UTC
