### ISSUE TITLE
failed test with various freetype version

### ISSUE THREAD

**Issue by remicollet** [libgd/libgd#363] opened 2017-01-18 15:41 UTC
2 tests have very erratic results, varying with freetype version

* freetype/bug00132 fails on RHEL-5 RHEL 6 and Fedora 26
* gdimagestringft/gdimagestringft_bbox fails on RHEL-5 and Fedora 26

Log (from Fedora 26)

```
# cat tests/gdimagestringft/gdimagestringft_bbox.log 
gdimagestringft/gdimagestringft_bbox.c:60: (491, 364) (613, 313) (602, 288) (481, 338) expected, but (491, 364) (613, 313) (602, 288) (480, 339)
FAIL gdimagestringft/gdimagestringft_bbox (exit status: 1)

# cat tests/freetype/bug00132.log 
freetype/bug00132.c:31: Total pixels changed: 9 with a maximum channel difference of 255.
freetype/bug00132.c:33: Reference image and destination differ
FAIL freetype/bug00132 (exit status: 1)

```

**Comment by cmb69** [comment] 2017-01-18 16:15
That's a duplicate of issue #302.

**Closed** 2017-01-19 18:05 UTC
Labels: duplicate
