### ISSUE TITLE
Can't process panoramic Samsung pictures.

### ISSUE THREAD

**Issue by peix2** [libgd/libgd#380] opened 2017-02-07 02:51 UTC
Hi,

I'm using Nextcloud with gallery app. Recently I've found that panoramic pictures cannot be viewed. 
Looking into logs I'm seeing errors like:
_"gd-jpeg: JPEG library reports unrecoverable error: Unsupported marker type 0x19" or
"gd-jpeg: JPEG library reports unrecoverable error: Unsupported JPEG process: SOF type 0xce"_

Using EOG (Eye of GNOME) I can view these pictures without an issue. 
Two examples of such can be seen here:
https://cph4.noip.pl/owncloud/index.php/s/6pLrp5OCGasgVQ4
https://cph4.noip.pl/owncloud/index.php/s/rA2OfY7LAP9BTLd

Cheers
Px2

**Comment by vapier** [comment] 2017-02-07 06:20
please attach an example image that does not work as well as the code you're using to process it

**Comment by peix2** [comment] 2017-02-07 06:37
Hi,


I did include links to pictures in description as files are over 40MB
and wouldn't be reasonable to include them directly.

About the code - I'm using NextCloud, which is OSS cloud (Google
services like in comparison) which is written in PHP and uses GD. Link
to to it here: https://nextcloud.com/install/#instructions-server

Sorry for maybe not so detailed input like you might be expecting but
I'm not Nextcloud developer nor PHP developer. Just admin of it who
found an issue.

I did report same issue on Nextcloud list but issue is with GD - not
with NC. NC uses GD to get image displayed.

Reported error messages are coming from GD and NC only passes this
message to logs to indicate issue.

If you need any more information I'm happy to help but would expect some
guidance from your side in term what/how to gather them.

Cheers

Px2




W dniu 07.02.2017 o 19:20, Mike Frysinger pisze:

**Comment by cmb69** [comment] 2017-02-07 12:01
It seems to me you're hitting https://bugs.php.net/bug.php?id=73479. Which PHP version do you use?

**Comment by peix2** [comment] 2017-02-07 19:36
ii  libgd3:amd64                                          2.1.1-4ubuntu0.16.04.5 
ii  php7.0                                                7.0.8-0ubuntu0.16.04.3

**Comment by cmb69** [comment] 2017-08-08 17:41
Sorry for the late reply. I wanted to have a closer look at this issue, but the links to images showing the behavior in the first post are dead, now. Scanning over the respective NextClound ticket didn't reveal any alternative links.

@peix2 Can you please post a link to an image that exhibits the behavior again?

**Comment by Der-Zohan** [comment] 2017-08-09 11:03
Feel free to try this one.
https://drive.google.com/file/d/0B9j2-FraTQYjSTVfZDJmb0UxcjA/view?usp=sharing
Same problem with lipjpeg-turbo

**Comment by cmb69** [comment] 2017-08-09 14:07
Thanks for the link, @Der-Zohan!

I've compared the behavior of PHP's bundled libgd and an external libgd, and while the former only raises a warning, the latter causes a fatal error. So indeed, we're hitting https://bugs.php.net/bug.php?id=73479 here, and as such this ticket is a duplicate of #338.

**Closed by cmb69** 2017-08-09 14:07 UTC
Labels: feedback requested
