### ISSUE TITLE
Test suite fails with freetype 2.7

### ISSUE THREAD

**Issue by DimStar77** [libgd/libgd#302] opened 2016-09-16 10:52 UTC
Freetype 2.7 has been released - but it seems libgd now fails the test suite.

Can't say (yet) if this is an issue in freetype itself or if libgd makes wrong / no longer valid assumptions

The failing test is:
FAIL: gdimagestringft/gdimagestringft_bbox

**Comment by cmb69** [comment] 2016-09-16 21:00
Thanks for reporting the issue!

However, I can't reproduce with a plain libfreetype 2.7.0 build. Can you please post tests/test-suite.log?

**Comment by DimStar77** [comment] 2016-09-17 11:21
of course - the content there is:

> 
> ====================================
>    GD 2.1.1: tests/test-suite.log
> ====================================
> 
> # TOTAL: 96
> # PASS:  95
> # SKIP:  0
> # XFAIL: 0
> # FAIL:  1
> # XPASS: 0
> # ERROR: 0
> 
> .. contents:: :depth: 2
> 
> FAIL: gdimagestringft/gdimagestringft_bbox
> ==========================================
> 
> (491, 364) (613, 313) (602, 288) (481, 338) expected, but (491, 364) (613, 313) (602, 288) (480, 339)
> FAIL gdimagestringft/gdimagestringft_bbox (exit status: 1)
>

**Comment by DimStar77** [comment] 2016-09-17 11:23
(I just see that we monitored the wrong site for updates though - http://libgd.bitbucket.org/ still lists 2.1.1 as latest version, whereas here on github there is 2.2.3 as latest; that might make a big difference)

**Comment by DimStar77** [comment] 2016-09-17 11:36
Tested a quick go with gd 2.2.3:
```

====================================
   GD 2.2.3: tests/test-suite.log
====================================

# TOTAL: 125
# PASS:  123
# SKIP:  0
# XFAIL: 0
# FAIL:  2
# XPASS: 0
# ERROR: 0

.. contents:: :depth: 2

FAIL: freetype/bug00132
=======================

freetype/bug00132.c:31: Total pixels changed: 9 with a maximum channel difference of 255.
freetype/bug00132.c:33: Reference image and destination differ
FAIL freetype/bug00132 (exit status: 1)

FAIL: gdimagestringft/gdimagestringft_bbox
==========================================

gdimagestringft/gdimagestringft_bbox.c:60: (491, 364) (613, 313) (602, 288) (481, 338) expected, but (491, 364) (613, 313) (602, 288) (480, 339)
FAIL gdimagestringft/gdimagestringft_bbox (exit status: 1)

```

**Comment by cmb69** [comment] 2016-09-17 11:38
Thanks! Obviously, there is only a small difference, and that might be caused by [rounding/precision issues](https://github.com/libgd/libgd/blob/gd-2.2.3/tests/gdimagestringft/gdimagestringft_bbox.c#L67-L69). At least for this test case we can probably hard-code the trigonometric values, what should solve the issue. I'll have a look at it.

Just noticed your update regarding GD 2.2.3; I'll have a look at the other failing test too.

Wrt. the website, <http://libgd.github.io/> is the official one now. The bitbucket site should ideally be redirected. @pierrejoye Can you please see to it?

**Comment by pierrejoye** [comment] 2016-09-17 12:55
Hi

There is no bitbucket Site anymore but the repos. We may just kill them. I
will check next week and move what we may want to keep before.

**Comment by DimStar77** [comment] 2016-09-17 13:00
> There is no bitbucket Site anymore but the repos. We may just kill them. I will check next week and move what we may want to keep before.

http://libgd.bitbucket.org/ => and as there is no comment I actually missed the move for a while (until I got more engaged in filing an issue)

**Comment by pierrejoye** [comment] 2016-09-17 13:19
Oh sorry. I will see if I can redirect it, thanks :)

**Comment by cmb69** [comment] 2016-09-17 15:01
Wrt. the failing gdimagestringft/gdimagestringft_bbox: can you please test cmb69/libgd@1df068b8eb87adbfc79c3db31e66546330c8ed16? I presume that this will still fail with the same result, but it's worth a try.

Wrt. the failing freetype/bug00132: while pixel-exact rendering of characters across FreeType versions and architectures would be desirable, this might not be possible at all, so we'd need a way to [compare images for similarity](https://github.com/libgd/libgd/issues/216), not for equality.

**Comment by DimStar77** [comment] 2016-09-17 15:11
> Wrt. the failing gdimagestringft/gdimagestringft_bbox: can you please test cmb69/libgd@1df068b? I presume that this will still fail with the same result, but it's worth a try.

Tested - fails the same way:
```

FAIL: gdimagestringft/gdimagestringft_bbox
==========================================

gdimagestringft/gdimagestringft_bbox.c:65: (491, 364) (613, 313) (602, 288) (481, 338) expected, but (491, 364) (613, 313) (602, 288) (480, 339)

```

**Comment by DimStar77** [comment] 2016-09-17 15:16
![bug00132 c_31_out](https://cloud.githubusercontent.com/assets/532559/18609113/57fa8d66-7cfa-11e6-9a97-6d976cef2b6f.png)

Just for reference, this is the produced image for the 'bug00132' test - freetype 2.7 bring a different default hinting style, which seems likely to be what we notice here?

**Comment by cmb69** [comment] 2016-09-17 15:20
> Tested - fails the same way:

Thanks for testing.

> freetype 2.7 bring a different default hinting style, which seems likely to be what we notice here?

That's possible, but in my environment the test succeeds. I used a simple `./configure` (w/o any args); did you pass arguments to your configure?

**Comment by DimStar77** [comment] 2016-09-17 15:23
Freetype is built using:

```
export CFLAGS=-fmessage-length=0 -grecord-gcc-switches -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -g -std=gnu99 -D_GNU_SOURCE
./configure \
        --with-bzip2 \
        --with-png \
        --with-zlib
```

**Comment by cmb69** [comment] 2016-09-17 15:48
Ah, I found the "culprit", it's libharfbuzz. Can you please confirm the adding `--with-harfbuzz=no` to configure would let the tests succeed?

Besides the slight differences caused by libharfbuzz, it obviously kills the alpha channel (what can be seen in the [reference image](https://github.com/libgd/libgd/issues/302#issuecomment-247780280) you've posted; at first I thought that was caused by the Github image upload). I'll have to do some investigation and debugging.

**Comment by DimStar77** [comment] 2016-09-17 15:58
> Ah, I found the "culprit", it's libharfbuzz. Can you please confirm the adding --with-harfbuzz=no to configure would let the tests succeed?

Sure - on gd or freetype?

in freetype's buildlog, I can already see:
```
[   23s] Library configuration:
[   23s]   external zlib: yes (pkg-config)
[   23s]   bzip2:         yes (pkg-config)
[   23s]   libpng:        yes (pkg-config)
[   23s]   harfbuzz:      no
```

**Comment by DimStar77** [comment] 2016-09-17 16:00
ok - you must have meant freetype - gd's configure has no harfbuzz config parameter.

So the strange thing then is that my freetype2 is already built without harfbuzz support

**Comment by cmb69** [comment] 2016-09-17 16:09
> So the strange thing then is that my freetype2 is already built without harfbuzz support

That's strange indeed. For me, only when freetype 2.7 is built with harfbuzz enabled, I get exactly the same test failures that you've reported. I don't get these failures, however, with freetype 2.6.5 with the same harfbuzz version.

Also, `TT_CONFIG_OPTION_SUBPIXEL_HINTING=0` doesn't make a difference.

**Comment by DimStar77** [comment] 2016-09-17 16:18
Tested with freetype explicitly configured with --with-harfbuzz=no and --with-harfbuzz=yes : the result for gd's test suite remained the same in my case

**Comment by cmb69** [comment] 2016-09-17 16:36
> Tested with freetype explicitly configured with --with-harfbuzz=no and --with-harfbuzz=yes : the result for gd's test suite remained the same in my case

Thanks. Anyhow, I don't think that we'll be able to make gdImageStringFT() to behave exactly identical for all possible configurations of FreeType (and most likely we don't even want to), and it might not be necessary to have exact tests – a suitable similarity check appears to be sufficient. And at least now I have a way to reproduce divergent behavior.

> Besides the slight differences caused by libharfbuzz, it obviously kills the alpha channel

Nonsense. Actually it's the test case (or maybe our test suite) that doesn't set the saveAlpha flag.

**Comment by david-geiger** [comment] 2016-10-03 07:33
Hi,

Confirmed here too, We have the same issue on Mageia with freetype 2.7:

FAIL: freetype/bug00132
FAIL: gdimagestringft/gdimagestringft_bbox
==============================================================
Testsuite summary for GD 2.2.3
==============================================================
# TOTAL: 126
# PASS:  124
# SKIP:  0
# XFAIL: 0
# FAIL:  2
# XPASS: 0
# ERROR: 0
===============================================================
See tests/test-suite.log
Please report to https://github.com/libgd/libgd/issues
===============================================================

**Comment by cmb69** [comment] 2016-10-11 22:43
Regarding `freetype/bug00132` I have found that the bitmap passed to gdft_draw_bitmap() may slightly differ for different FreeType versions/configurations. The issue *might* be due to libgd neither using FT_Render_Glyph() nor FT_LOAD_RENDER.

Anyhow, the test is supposed to test that `&thetasym;` can be rendered (see commit 464ec3e0), and the most perceptual difference between the results is caused by disabled anti-aliased rendering which is [enforced by the test](https://github.com/libgd/libgd/blob/gd-2.2.3/tests/freetype/bug00132.c#L25) (anti-aliased rendering is disabled when negative integers are passed as color). Passing `0xffffff` as color instead would make the results "perceptually indistinguishable" according to perceptualdiff and quick manual inspection (contrary to the "un-anti-aliased" images); the current gdAssertImageEqualsToFile() would still fail (even worse, actually).

Also the mapping of the alpha values – supplied in the bitmap delivered by FreeType – to GD's alpha values might need review. Especially note the [`FT_Render_Glyph()` documentation](https://www.freetype.org/freetype2/docs/reference/ft2-base_interface.html#FT_Render_Glyph).

**Comment by omron93** [comment] 2016-12-05 12:58
@cmb69 Anything how to make two mentioned tests fixed with freetype 2.7?

**Comment by croth1** [comment] 2017-01-15 16:12
are there already patches available for fixing the test suite?

**Comment by cmb69** [comment] 2017-01-16 16:22
> are there already patches available for fixing the test suite?

No, sorry. The biggest issue is that we would need some image similarity check in our test suite, but we have not yet decided which one, let alone come to implement it.

**Comment by cmb69** [comment] 2017-01-25 18:18
> freetype 2.7 bring a different default hinting style, which seems likely to be what we notice here?

Indeed, you've been right. Running the tests with `FREETYPE_PROPERTIES=truetype:interpreter-version=35` lets them pass again (Windows & Linux).

**Comment by cmb69** [comment] 2017-01-25 22:42
For reference: https://www.freetype.org/freetype2/docs/subpixel-hinting.html.

**Closed** 2017-01-29 16:16 UTC
