### ISSUE TITLE
Unable to build libgd of Solaris 10 with Sun studio compiler

### ISSUE THREAD

**Issue by w112087** [libgd/libgd#619] opened 2020-04-03 08:35 UTC
Hi Team,

I'm trying to build libgd-2.3.0 on Solaris 10:

$ uname -a
SunOS XXXXXXXXXXXX.net 5.10 Generic_150400-63 sun4v sparc sun4v

$ cat /etc/release
                   Oracle Solaris 10 1/13 s10s_u11wos_24a SPARC
  Copyright (c) 1983, 2013, Oracle and/or its affiliates. All rights reserved.
                            Assembled 17 January 2013

$ cc -V
cc: Studio 12.6 Sun C 5.15 SunOS_sparc 2017/05/30

The configure works fine.

However the "make" bit always fails as below:

make -C libgd-2.3.0 all
make[1]: Entering directory `/prod/build/user1/gsa/libgd/libgd-2.3.0'
Making all in src
make[2]: Entering directory `/prod/build/user1/gsa/libgd/libgd-2.3.0/src'
make  all-am
make[3]: Entering directory `/prod/build/user1/gsa/libgd/libgd-2.3.0/src'
/bin/bash ../libtool  --tag=CC   --mode=link /prod/sun-studio/current/bin/cc  -xO4 -xchip=generic -m32     -o annotate annotate.o libgd.la /prod/libiconv/current//lib/libiconv.so -R/prod/libiconv/current//lib -lm    -lz -L/prod/libpng/current//lib -L/prod/libpng/current/lib -R/prod/libpng/current/lib -lpng16 -L/prod/freetype/current//lib -L/prod/freetype/current/lib -lfreetype -L/prod/libjpeg/current//lib  -ljpeg   -lXpm -L/prod/libtiff/current//lib  -ltiff
libtool: link: /prod/sun-studio/current/bin/cc -xO4 -xchip=generic -m32 -o .libs/annotate annotate.o /prod/libiconv/current//lib/libiconv.so  ./.libs/libgd.so -L/prod/libiconv/current//lib /prod/libiconv/current/lib/libiconv.so -L/prod/libpng/current//lib -L/prod/libpng/current/lib -L/prod/freetype/current//lib -L/prod/freetype/current/lib -L/usr/lib -L/prod/libjpeg/current//lib -L/prod/libtiff/current//lib -L/prod/libjpeg/current/lib /prod/freetype/current/lib/libfreetype.so /prod/libpng/current/lib/libpng16.so -lbz2 -lpng12 -lXpm /prod/libtiff/current/lib/libtiff.so /prod/libjpeg/current/lib/libjpeg.so -lz -lm -R/prod/libgd/current/lib -R/prod/libiconv/current/lib -R/prod/libpng/current/lib -R/prod/freetype/current/lib -R/prod/libjpeg/current/lib -R/prod/libtiff/current/lib -R/prod/libiconv/current//lib
ld: warning: file /prod/libiconv/current/lib/libiconv.so: linked to /prod/libiconv/current//lib/libiconv.so: attempted multiple inclusion of file
Undefined                       first referenced
 symbol                             in file
getline                             annotate.o
ld: fatal: symbol referencing errors. No output written to .libs/annotate
make[3]: *** [annotate] Error 2
make[3]: Leaving directory `/prod/build/user1/gsa/libgd/libgd-2.3.0/src'
make[2]: *** [all] Error 2
make[2]: Leaving directory `/prod/build/user1/gsa/libgd/libgd-2.3.0/src'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/prod/build/user1/gsa/libgd/libgd-2.3.0'
make: *** [libgd-2.3.0/.build_done] Error 2

If I repeat the process but using the libgd 2.2.5 release I can successfully build the software and libraries etc.

Please can you take a look and advise. Any help/support much appreciated as we're using this library in other software on our Solaris 10 build.

Many thanks and keep up the great work

**Comment by cmb69** [comment] 2020-04-03 08:45
This appears to be a duplicate of #611 (see https://github.com/libgd/libgd/issues/611#issuecomment-605640297).

**Comment by w112087** [comment] 2020-04-03 09:56
Hi,

Thanks very much for the quick response.  I've taken a look at #611 and implemented the "annotate.c" patch changing "#ifdef _WIN32" to "#ifdef sun".  I used patch "posix_memalign" in gd_topal.c  as was.

And "boom" libgd 2.3.0 compiles in both 32 & 64 bit.  

Thanks so much you've made my day :)

Please feel free to close this call/ticket.

**Comment by cmb69** [comment] 2020-04-03 10:45
Great! :)

**Closed by cmb69** 2020-04-03 10:45 UTC
