### ISSUE TITLE
gdimagesquaretocircle failing with 2.3.0: OS-X without PNG

### ISSUE THREAD

**Issue by ChrisBarker-NOAA** [libgd/libgd#662] opened 2020-11-24 00:43 UTC
I *think* the issue here is that the gdimagesquaretocircle test shouldn't be running when libgd was built without libpng -- as the rest requires reading a PNG file.

To repeat:

I did a plain:

```
./configure
make 
make check
```

and all mostly went well, but getting a failure with 

```
...
FAIL: gdimagesquaretocircle/gdimagesquaretocircle
```
all the others pass:

```
============================================================================
Testsuite summary for GD 2.3.0
============================================================================
# TOTAL: 97
# PASS:  96
# SKIP:  0
# XFAIL: 0
# FAIL:  1
# XPASS: 0
# ERROR: 0
```

OS-X 10.13.6

```
$ clang --version
Apple LLVM version 10.0.0 (clang-1000.10.44.4)
Target: x86_64-apple-darwin17.7.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```

**Comment by cmb69** [comment] 2020-11-24 13:41
Duplicate of issue #616.

**Closed by cmb69** 2020-11-24 13:41 UTC
Labels: duplicate

**Comment by ChrisBarker-NOAA** [comment] 2020-12-01 23:27
already fixed --  thanks!
